version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg18
    container_name: postgres-vector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      # 持久化資料庫檔案 (確保重開機資料還在)
      - pgdata:/var/lib/postgresql
      
      # 將本地的 init.sql 掛載到容器的初始化目錄
      - ./backend/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: